#!/usr/bin/env ruby
require 'sqlite3'
require './bootstrap_ar'
require 'csv'
require './modules/import_data_into_db.rb'

# ARGV = [add, foo]
command = ARGV[0]

if command == "add"
  project_name = ARGV[1]
  User.create(firstname: project_name)
elsif command == "list"
  all_users = User.all
  all_users.each_with_index do |user, i|
    puts "#{i+1}. #{user.firstname}"
  end
elsif command == "delete_all_records"
  matching_projects = User.all
  matching_projects.each do |user|
    User.destroy_all
    puts "All Data Entries Deleted"
  end
elsif command == "-i"
  User.destroy_all
  filename = ARGV[1]
  write_user_info_to_db(filename)

elsif command == "-fn"
  firstname = ARGV[1]
  all_users = User.all
  all_users.each do |user|
  # puts "user = #{user.firstname}"
    if user.firstname.downcase.include?(firstname.downcase)
      # puts "firstname = #{user.firstname}"
      clean_phone = user.phone.gsub(".","-")
      result = "\n==================\e[47m\nName:   #{user.firstname} #{user.lastname}\e[0m\nEmail:  #{user.email}\n\e[47mPhone:  #{clean_phone}\e[0m\nGithub: #{user.github}\n\e[47mTown:   #{user.part_of_town}\e[0m\n\n"
      puts "\nPhone Results#{result}"
    end
  end


elsif command == "-ln"
  lastname = ARGV[1]
  all_users = User.all
  all_users.each do |user|
  # puts "user = #{user.firstname}"
    if user.lastname.downcase.include?(lastname.downcase)
      # puts "firstname = #{user.firstname}"
      clean_phone = user.phone.gsub(".","-")
      result = "\n==================\e[47m\nName:   #{user.firstname} #{user.lastname}\e[0m\nEmail:  #{user.email}\n\e[47mPhone:  #{clean_phone}\e[0m\nGithub: #{user.github}\n\e[47mTown:   #{user.part_of_town}\e[0m\n\n"
      puts "\nPhone Results#{result}"
    end

  end

elsif command == "-town"
  part_of_town = ARGV[1]
  all_users = User.all
  all_users.each do |user|
  # puts "user = #{user.firstname}"
    if user.part_of_town.downcase.include?(part_of_town.downcase)
      # puts "firstname = #{user.firstname}"
      clean_phone = user.phone.gsub(".","-")
      result = "\n==================\e[47m\nName:   #{user.firstname} #{user.lastname}\e[0m\nEmail:  #{user.email}\n\e[47mPhone:  #{clean_phone}\e[0m\nGithub: #{user.github}\n\e[47mTown:   #{user.part_of_town}\e[0m\n\n"
      puts "\nPhone Results#{result}"
    end
  end


end

# end
